### PR TITLE
Milestone 6 - Create model with associations and all requested features for friendships.

### PR DESCRIPTION
**Pull request by RyelBanfield**
This PR is just for submission purposes. Please view this PR as the last reviewer said I already implemented the features needed for this one and then the second reviewer said my project was completed. - https://github.com/RyelBanfield/ror-social-scaffold/pull/2

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Ryel Banfield** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] you should follow the requested git flow: production `master` branch + main `development` branch + Pull Requests from feature branches to the `develop`
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by RyelBanfield** [comment]
Not sure what you mean as there is a `master` branch that I have not touched yet. There is a `development` branch that is my `default` or `main` and I pull from my feature branches which are named after the milestone. @andresporras3423 Please explain.

**Review by enaburekhan — APPROVED** [review]
# Status: Approve:heavy_check_mark:
**Hi Banfield!
Congratulations on this milestone. Thank you for implementing the changes requested by the last reviewer.**
I will encourage you to implement the below optional change before merging the PR.  This will make the codebase to be more professional.

**Optional**

- [ ] It would be nice to move the logic in `application.html.erb` under layout in view to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) if you need a refresher on how to use a helper in rails. See [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by RyelBanfield** [comment]
Thank you for your review. I have noted your recommendation but will be implementing it in my own personal side project.

**Pull request merged**
